version: '3'
services:
  app:
    build: .
    container_name: todo-app-supabase
    environment:
      - DATABASE_URL=postgresql://postgres.cbezsrqlbahyyzrpdbut:Raj@rajthegreat0604@aws-0-ap-south-1.pooler.supabase.com:6543/postgres?pgbouncer=true
      - JWT_SECRET=your_jwt_secret_here
      - NODE_ENV=development
      - PORT=5000
    ports:
      - "5000:5000"
    volumes:
      - .:/app 